### ISSUE TITLE
redist_shortbust no longer working in dev

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/redist#114] opened 2021-11-08 09:16 UTC
In the dev version I installed yesterday (2021-11-07), shortburst errors out. I can replicate the error message with the man page example below.

It works fine in the redist package dev version as of  251b9dbc7468cb7360700aecb7fd693a8a685408 (2021-11-03).

``` r
library(redist) # version 5949b (2021-11-07)
#> Warning: package 'redist' was built under R version 4.0.5
#> 
#> Attaching package: 'redist'
#> The following object is masked from 'package:stats':
#> 
#>     filter

data(iowa)

iowa_map = redist_map(iowa, existing_plan=cd_2010, pop_tol=0.01)
redist_shortburst(iowa_map, scorer_frac_kept(iowa_map), max_bursts=50)
#> MERGE-SPLIT SHORT BURSTS
#> Sampling up to 50 bursts of 10 iterations each.
#> Burst  Improve?  Score
#> Error in ms_plans(burst_size + 1L, adj, init, counties, pop, ndists, pop_bounds[2], : Expecting a single value: [extent=0].
```

<sup>Created on 2021-11-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Can include my sessionInfo if it's local depenendent. @CoryMcCartan @christopherkenny

**Comment by CoryMcCartan** [comment] 2021-11-08 16:38
Thanks; this was caused by a change in verbosity reporting levels. Now fixed

**Closed by CoryMcCartan** 2021-11-08 16:38 UTC
